'use client';

import { useEffect, useRef } from 'react';
import { X, Plus } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { CHOICE_FIELD_TYPES } from '../types';
import type { FieldType } from '@/modules/form/types';

const NO_PLACEHOLDER_TYPES = ['STATEMENT', 'PAGE_BREAK', 'FILE_UPLOAD', 'RATING', 'SCALE', 'CHECKBOX'];
const NO_REQUIRED_TYPES = ['STATEMENT', 'PAGE_BREAK'];

interface BlockConfigPopoverProps {
  attrs: {
    fieldType: string;
    label: string;
    description: string;
    placeholder: string;
    required: boolean;
    options: string;
  };
  onUpdate: (updates: Record<string, unknown>) => void;
  onClose: () => void;
}

export function BlockConfigPopover({ attrs, onUpdate, onClose }: BlockConfigPopoverProps) {
  const ref = useRef<HTMLDivElement>(null);
  const fieldType = attrs.fieldType as FieldType;
  const showPlaceholder = !NO_PLACEHOLDER_TYPES.includes(fieldType);
  const showRequired = !NO_REQUIRED_TYPES.includes(fieldType);
  const showOptions = CHOICE_FIELD_TYPES.includes(fieldType);

  let parsedOptions: { label: string; value: string }[] = [];
  try {
    parsedOptions = JSON.parse(attrs.options || '[]');
  } catch {
    parsedOptions = [];
  }

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        onClose();
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [onClose]);

  function addOption() {
    const updated = [...parsedOptions, { label: '', value: '' }];
    onUpdate({ options: JSON.stringify(updated) });
  }

  function removeOption(index: number) {
    const updated = parsedOptions.filter((_, i) => i !== index);
    onUpdate({ options: JSON.stringify(updated) });
  }

  function updateOption(index: number, key: 'label' | 'value', val: string) {
    const updated = parsedOptions.map((opt, i) => {
      if (i !== index) return opt;
      if (key === 'label') {
        const autoValue = opt.label.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
        const isAutoGenerated = opt.value === '' || opt.value === autoValue;
        const newValue = isAutoGenerated
          ? val.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '')
          : opt.value;
        return { label: val, value: newValue };
      }
      return { ...opt, [key]: val };
    });
    onUpdate({ options: JSON.stringify(updated) });
  }

  return (
    <div
      ref={ref}
      className="absolute right-0 top-0 z-50 w-72 rounded-lg border bg-popover p-4 shadow-lg space-y-3"
      onClick={(e) => e.stopPropagation()}
    >
      <div className="flex items-center justify-between">
        <h4 className="text-sm font-semibold">Configure field</h4>
        <button type="button" onClick={onClose} className="p-1 rounded hover:bg-muted">
          <X className="h-3.5 w-3.5" />
        </button>
      </div>

      <Separator />

      <div className="space-y-3">
        <div className="space-y-1.5">
          <Label htmlFor="cfg-label">Label</Label>
          <Input
            id="cfg-label"
            value={attrs.label}
            onChange={(e) => onUpdate({ label: (e.target as HTMLInputElement).value })}
            placeholder="Field label"
          />
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="cfg-desc">Description</Label>
          <Input
            id="cfg-desc"
            value={attrs.description}
            onChange={(e) => onUpdate({ description: (e.target as HTMLInputElement).value || null })}
            placeholder="Help text (optional)"
          />
        </div>

        {showPlaceholder && (
          <div className="space-y-1.5">
            <Label htmlFor="cfg-placeholder">Placeholder</Label>
            <Input
              id="cfg-placeholder"
              value={attrs.placeholder}
              onChange={(e) => onUpdate({ placeholder: (e.target as HTMLInputElement).value || null })}
              placeholder="Placeholder text"
            />
          </div>
        )}

        {showRequired && (
          <div className="flex items-center justify-between">
            <Label>Required</Label>
            <Button
              type="button"
              variant={attrs.required ? 'default' : 'outline'}
              size="sm"
              onClick={() => onUpdate({ required: !attrs.required })}
            >
              {attrs.required ? 'Required' : 'Optional'}
            </Button>
          </div>
        )}
      </div>

      {showOptions && (
        <>
          <Separator />
          <div className="space-y-2">
            <Label>Options</Label>
            {parsedOptions.map((opt, i) => (
              <div key={i} className="flex items-center gap-1.5">
                <Input
                  placeholder="Label"
                  value={opt.label}
                  onChange={(e) => updateOption(i, 'label', (e.target as HTMLInputElement).value)}
                  className="flex-1 h-8 text-xs"
                />
                <button
                  type="button"
                  onClick={() => removeOption(i)}
                  className="p-1 rounded hover:bg-destructive/10 text-muted-foreground hover:text-destructive shrink-0"
                >
                  <X className="h-3 w-3" />
                </button>
              </div>
            ))}
            <Button type="button" variant="outline" size="sm" onClick={addOption} className="w-full h-7 text-xs">
              <Plus className="mr-1 h-3 w-3" />
              Add option
            </Button>
          </div>
        </>
      )}
    </div>
  );
}
