export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_OTP: '/verify-otp',
  COMPLETE_PROFILE: '/complete-profile',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',

  HOME: '/',
  SETTINGS: '/settings',
  SEARCH: '/search',
  DOMAINS: '/domains',
  UPGRADE: '/upgrade',
  PRICING: '/pricing',
  TEMPLATES: '/templates',
  WHATS_NEW: '/whats-new',
  ROADMAP: '/roadmap',
  FEATURE_REQUESTS: '/feature-requests',
  REWARDS: '/rewards',
  TRASH: '/trash',
  GET_STARTED: '/get-started',
  GUIDES: '/guides',
  HELP_CENTER: '/help-center',
  CONTACT_SUPPORT: '/contact-support',
  MEMBERS: '/members',
  WORKSPACES: '/workspaces',
  NEW_WORKSPACE: '/workspaces/new',

  workspace: (workspaceId: string) => ({
    ROOT: `/${workspaceId}`,
    FORMS: `/${workspaceId}/forms`,
    NEW_FORM: `/${workspaceId}/forms/new`,
    form: (formId: string) => ({
      ROOT: `/${workspaceId}/forms/${formId}`,
      EDIT: `/${workspaceId}/forms/${formId}/edit`,
      SUBMISSIONS: `/${workspaceId}/forms/${formId}/submissions`,
      ANALYTICS: `/${workspaceId}/forms/${formId}/analytics`,
      SETTINGS: `/${workspaceId}/forms/${formId}/settings`,
    }),
    MEMBERS: `/${workspaceId}/members`,
    SETTINGS: `/${workspaceId}/settings`,
    BILLING: `/${workspaceId}/billing`,
    UPGRADE: `/${workspaceId}/upgrade`,
  }),

  publicForm: (slug: string) => `/f/${slug}`,
  publicFormSuccess: (slug: string) => `/f/${slug}/success`,
  SANDBOX: '/sandbox',
} as const;
